### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by boehser-enkel** [containrrr/watchtower#1163]
**Describe the bug**
```
time="2021-12-16T11:01:34Z" level=info msg="Found new ghcr.io/linuxserver/daapd:latest image (2b30c802afee)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x501f54]
goroutine 1 [running]:
github.com/containrrr/watchtower/pkg/registry/digest.CompareDigest(0x85c6b8, 0x2abc880, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/watchtower/watchtower/pkg/registry/digest/digest.go:43 +0x160
github.com/containrrr/watchtower/pkg/container.dockerClient.PullImage(0x85dc78, 0x2ae7f80, 0x10001, 0x1, 0x0, 0x0, 0x8573f0, 0x282a490, 0x2d50000, 0x2d96380, ...)
	/home/runner/work/watchtower/watchtower/pkg/container/client.go:315 +0x35c
github.com/containrrr/watchtower/pkg/container.dockerClient.IsContainerStale(0x85dc78, 0x2ae7f80, 0x10001, 0x1, 0x0, 0x0, 0x780000, 0x2d96380, 0x0, 0x50c100, ...)
	/home/runner/work/watchtower/watchtower/pkg/container/client.go:267 +0x70
github.com/containrrr/watchtower/internal/actions.Update(0x85a968, 0x2afa340, 0x2afe298, 0x1, 0x540be400, 0x2, 0x10000, 0x0, 0x0, 0x0)
	/home/runner/work/watchtower/watchtower/internal/actions/update.go:34 +0x140
github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0x2afe298, 0x0)
	/home/runner/work/watchtower/watchtower/cmd/root.go:334 +0xb0
github.com/containrrr/watchtower/cmd.Run(0x29266e0, 0x2a298f0, 0x0, 0x5)
	/home/runner/work/watchtower/watchtower/cmd/root.go:173 +0x534
github.com/spf13/cobra.(*Command).execute(0x29266e0, 0x2824068, 0x5, 0x5, 0x29266e0, 0x2824068)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x1e8
github.com/spf13/cobra.(*Command).ExecuteC(0x29266e0, 0x285e070, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x250
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/containrrr/watchtower/cmd.Execute()
	/home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x20
main.main()
	/home/runner/work/watchtower/watchtower/main.go:13 +0x14
```

**To Reproduce**
```
docker run -d \
--name watchtower \
-v /var/run/docker.sock:/var/run/docker.sock \
containrrr/watchtower \
--cleanup \
--include-restarting \
--include-stopped \
--rolling-restart
```

**Expected behavior**
Updates

**Screenshots**

**Environment**
Raspberry Pi with Raspbian

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
2021-12-16T11:13:38Z [D] Got image name: louislam/uptime-kuma:1
2021-12-16T11:13:38Z [D] Checking if pull is needed
                         container: /uptime-kuma
                         image: louislam/uptime-kuma:1
2021-12-16T11:13:38Z [D] Building challenge URL
                         URL: https://index.docker.io/v2/
2021-12-16T11:13:38Z [D] Got response to challenge request
                         header: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
                         status: 401 Unauthorized
2021-12-16T11:13:38Z [D] Checking challenge header content
                         realm: https://auth.docker.io/token
                         service: registry.docker.io
2021-12-16T11:13:38Z [D] Setting scope for auth token
                         image: louislam/uptime-kuma
                         scope: repository:louislam/uptime-kuma:pull
2021-12-16T11:13:38Z [D] No credentials found.
2021-12-16T11:13:38Z [D] Parsing image ref
                         host: index.docker.io
                         image: louislam/uptime-kuma
                         normalized: docker.io/louislam/uptime-kuma:1
                         tag: 1
2021-12-16T11:13:38Z [D] Doing a HEAD request to fetch a digest
                         url: https://index.docker.io/v2/louislam/uptime-kuma/manifests/1
2021-12-16T11:13:39Z [D] Found a remote digest to compare with
                         remote: sha256:9fd26d8adae499533e0079f218b4c9139e89b3a085ec04b246c3fbf7af04aa62
2021-12-16T11:13:39Z [D] Comparing
                         local: sha256:e12dc0c30287b9c72d6ed3c7a49f6593343273f6dd71bea1cacd9c2abbb52019
                         remote: sha256:9fd26d8adae499533e0079f218b4c9139e89b3a085ec04b246c3fbf7af04aa62
2021-12-16T11:13:39Z [D] Digests did not match, doing a pull.
2021-12-16T11:13:39Z [D] Pulling image
                         container: /uptime-kuma
                         image: louislam/uptime-kuma:1
2021-12-16T11:13:40Z [I] Found new louislam/uptime-kuma:1 image (ccea3a511bcc)
2021-12-16T11:13:40Z [D] Trying to load authentication credentials.
                         container: /nginx_proxy_manager
                         image: jc21/nginx-proxy-manager:latest
2021-12-16T11:13:40Z [D] No credentials for jc21 found
                         config_file: /config.json
2021-12-16T11:13:40Z [D] Got image name: jc21/nginx-proxy-manager:latest
2021-12-16T11:13:40Z [D] Checking if pull is needed
                         container: /nginx_proxy_manager
                         image: jc21/nginx-proxy-manager:latest
2021-12-16T11:13:40Z [D] Building challenge URL
                         URL: https://index.docker.io/v2/
2021-12-16T11:13:40Z [D] Got response to challenge request
                         header: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
                         status: 401 Unauthorized
2021-12-16T11:13:41Z [D] Checking challenge header content
                         realm: https://auth.docker.io/token
                         service: registry.docker.io
2021-12-16T11:13:41Z [D] Setting scope for auth token
                         image: jc21/nginx-proxy-manager
                         scope: repository:jc21/nginx-proxy-manager:pull
2021-12-16T11:13:41Z [D] No credentials found.
2021-12-16T11:13:41Z [D] Parsing image ref
                         host: index.docker.io
                         image: jc21/nginx-proxy-manager
                         normalized: docker.io/jc21/nginx-proxy-manager:latest
                         tag: latest
2021-12-16T11:13:41Z [D] Doing a HEAD request to fetch a digest
                         url: https://index.docker.io/v2/jc21/nginx-proxy-manager/manifests/latest
2021-12-16T11:13:41Z [D] Found a remote digest to compare with
                         remote: sha256:e1f39cc38aaeb6302933e4c782089e87fe5bf4fdec79e62e645d4cdcdc97e4e4
2021-12-16T11:13:41Z [D] Comparing
                         local: sha256:3c9a801a882d3d0d2ab45765e820a82fa3258dfdb302ea78ca7705650e028c7c
                         remote: sha256:e1f39cc38aaeb6302933e4c782089e87fe5bf4fdec79e62e645d4cdcdc97e4e4
2021-12-16T11:13:41Z [D] Digests did not match, doing a pull.
2021-12-16T11:13:41Z [D] Pulling image
                         container: /nginx_proxy_manager
                         image: jc21/nginx-proxy-manager:latest
2021-12-16T11:13:42Z [I] Found new jc21/nginx-proxy-manager:latest image (a8852b4a5133)
2021-12-16T11:13:42Z [D] Trying to load authentication credentials.
                         container: /nginxdb
                         image: jc21/mariadb-aria:latest
2021-12-16T11:13:42Z [D] No credentials for jc21 found
                         config_file: /config.json
2021-12-16T11:13:42Z [D] Got image name: jc21/mariadb-aria:latest
2021-12-16T11:13:42Z [D] Checking if pull is needed
                         container: /nginxdb
                         image: jc21/mariadb-aria:latest
2021-12-16T11:13:42Z [D] Building challenge URL
                         URL: https://index.docker.io/v2/
2021-12-16T11:13:43Z [D] Got response to challenge request
                         header: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
                         status: 401 Unauthorized
2021-12-16T11:13:43Z [D] Checking challenge header content
                         realm: https://auth.docker.io/token
                         service: registry.docker.io
2021-12-16T11:13:43Z [D] Setting scope for auth token
                         image: jc21/mariadb-aria
                         scope: repository:jc21/mariadb-aria:pull
2021-12-16T11:13:43Z [D] No credentials found.
2021-12-16T11:13:43Z [D] Parsing image ref
                         host: index.docker.io
                         image: jc21/mariadb-aria
                         normalized: docker.io/jc21/mariadb-aria:latest
                         tag: latest
2021-12-16T11:13:43Z [D] Doing a HEAD request to fetch a digest
                         url: https://index.docker.io/v2/jc21/mariadb-aria/manifests/latest
2021-12-16T11:13:44Z [D] Found a remote digest to compare with
                         remote: sha256:9dafab05f863cd186101fd8ac8b18684e8dfd7c3cce1376e552b77d0a8b40839
2021-12-16T11:13:44Z [D] Comparing
                         local: sha256:bc9d4cc44bab21f73b9ff037bb51c8e6968c7f5f4ed815ee446fdbe9c45eb90b
                         remote: sha256:9dafab05f863cd186101fd8ac8b18684e8dfd7c3cce1376e552b77d0a8b40839
2021-12-16T11:13:44Z [D] Digests did not match, doing a pull.
2021-12-16T11:13:44Z [D] Pulling image
                         container: /nginxdb
                         image: jc21/mariadb-aria:latest
2021-12-16T11:13:45Z [I] Found new jc21/mariadb-aria:latest image (26f81c780271)
2021-12-16T11:13:45Z [D] Trying to load authentication credentials.
                         container: /daapd
                         image: ghcr.io/linuxserver/daapd:latest
2021-12-16T11:13:45Z [D] No credentials for ghcr.io found
                         config_file: /config.json
2021-12-16T11:13:45Z [D] Got image name: ghcr.io/linuxserver/daapd:latest
2021-12-16T11:13:45Z [D] Checking if pull is needed
                         container: /daapd
                         image: ghcr.io/linuxserver/daapd:latest
2021-12-16T11:13:45Z [D] Building challenge URL
                         URL: https://ghcr.io/v2/
2021-12-16T11:13:45Z [D] Got response to challenge request
                         header: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:user/image:pull"
                         status: 401 Unauthorized
2021-12-16T11:13:45Z [D] Checking challenge header content
                         realm: https://ghcr.io/token
                         service: ghcr.io
2021-12-16T11:13:45Z [D] Setting scope for auth token
                         image: ghcr.io/linuxserver/daapd
                         scope: repository:ghcr.io/linuxserver/daapd:pull
2021-12-16T11:13:45Z [D] No credentials found.
2021-12-16T11:13:45Z [D] Parsing image ref
                         host: ghcr.io
                         image: linuxserver/daapd
                         normalized: ghcr.io/linuxserver/daapd:latest
                         tag: latest
2021-12-16T11:13:45Z [D] Doing a HEAD request to fetch a digest
                         url: https://ghcr.io/v2/linuxserver/daapd/manifests/latest
2021-12-16T11:13:45Z [D] Found a remote digest to compare with
                         remote: sha256:ff1577f8ee0dddb995e033622f83e642e70899884b59b3f1a9471e4090e9e3a1
2021-12-16T11:13:45Z [D] Comparing
                         local: sha256:0d47cb8d5ccd78872ec78e88c5902746ba0314d3766007f35fe8d9121136ae8d
                         remote: sha256:ff1577f8ee0dddb995e033622f83e642e70899884b59b3f1a9471e4090e9e3a1
2021-12-16T11:13:45Z [D] Digests did not match, doing a pull.
2021-12-16T11:13:45Z [D] Pulling image
                         container: /daapd
                         image: ghcr.io/linuxserver/daapd:latest
2021-12-16T11:13:46Z [I] Found new ghcr.io/linuxserver/daapd:latest image (2b30c802afee)
2021-12-16T11:13:46Z [D] Trying to load authentication credentials.
                         container: /iobroker
                         image: buanet/iobroker:latest
2021-12-16T11:13:46Z [D] No credentials for buanet found
                         config_file: /config.json
2021-12-16T11:13:46Z [D] Got image name: buanet/iobroker:latest
2021-12-16T11:13:46Z [D] Checking if pull is needed
                         container: /iobroker
                         image: buanet/iobroker:latest
2021-12-16T11:13:46Z [D] Building challenge URL
                         URL: https://index.docker.io/v2/
2021-12-16T11:13:46Z [D] Got response to challenge request
                         header: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
                         status: 401 Unauthorized
2021-12-16T11:13:47Z [D] Checking challenge header content
                         realm: https://auth.docker.io/token
                         service: registry.docker.io
2021-12-16T11:13:47Z [D] Setting scope for auth token
                         image: buanet/iobroker
                         scope: repository:buanet/iobroker:pull
2021-12-16T11:13:47Z [D] No credentials found.
2021-12-16T11:13:47Z [D] Parsing image ref
                         host: index.docker.io
                         image: buanet/iobroker
                         normalized: docker.io/buanet/iobroker:latest
                         tag: latest
2021-12-16T11:13:47Z [D] Doing a HEAD request to fetch a digest
                         url: https://index.docker.io/v2/buanet/iobroker/manifests/latest
2021-12-16T11:13:47Z [D] Found a remote digest to compare with
                         remote: sha256:1f4a1161d1b8ed6ec71e9e1e6511cef72f3422a671cfb7919b7e0ceee3130eed

panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x501f54],
goroutine 1 [running]:,
github.com/containrrr/watchtower/pkg/registry/digest.CompareDigest(0x85c6b8, 0x27ae050, 0x0, 0x0, 0x0, 0x0, 0x0),
	/home/runner/work/watchtower/watchtower/pkg/registry/digest/digest.go:43 +0x160,
github.com/containrrr/watchtower/pkg/container.dockerClient.PullImage(0x85dc78, 0x274df00, 0x10001, 0x1, 0x0, 0x0, 0x8573f0, 0x242a490, 0x28b0000, 0x276c8c0, ...),
	/home/runner/work/watchtower/watchtower/pkg/container/client.go:315 +0x35c,
github.com/containrrr/watchtower/pkg/container.dockerClient.IsContainerStale(0x85dc78, 0x274df00, 0x10001, 0x1, 0x0, 0x0, 0x780000, 0x276c8c0, 0x0, 0x50c100, ...),
	/home/runner/work/watchtower/watchtower/pkg/container/client.go:267 +0x70,
github.com/containrrr/watchtower/internal/actions.Update(0x85a968, 0x2750f40, 0x27035f8, 0x1, 0x540be400, 0x2, 0x10000, 0x0, 0x0, 0x0),
	/home/runner/work/watchtower/watchtower/internal/actions/update.go:34 +0x140,
github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0x27035f8, 0x0),
	/home/runner/work/watchtower/watchtower/cmd/root.go:334 +0xb0,
github.com/containrrr/watchtower/cmd.Run(0x25ba420, 0x26eb2c0, 0x0, 0x6),
	/home/runner/work/watchtower/watchtower/cmd/root.go:173 +0x534,
github.com/spf13/cobra.(*Command).execute(0x25ba420, 0x2424148, 0x6, 0x7, 0x25ba420, 0x2424148),
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x1e8,
github.com/spf13/cobra.(*Command).ExecuteC(0x25ba420, 0x245e070, 0x0, 0x0),
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x250,
github.com/spf13/cobra.(*Command).Execute(...),
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883,
github.com/containrrr/watchtower/cmd.Execute(),
	/home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x20,
main.main(),
	/home/runner/work/watchtower/watchtower/main.go:13 +0x14
```

</details>

**Additional context**

**Comment by piksel** [comment]
OK, so either `ImageInfo` is nil, or it's `RepoDigests` field:
https://github.com/containrrr/watchtower/blob/cc3ff5a58803e327dc811d06e9fe3fe5ce512704/pkg/registry/digest/digest.go#L43

Not sure what to make of that...

**Comment by boehser-enkel** [comment]
Is this a problem with a certain docker image or with my system as a whole?

**Comment by piksel** [comment]
No idea. Never seen this happen before. Could you try running
`docker inspect buanet/iobroker:latest`

**Comment by boehser-enkel** [comment]
`Error: No such object: buanet/iobroker:latest`

For docker inspect iobroker

```json
[
    {
        "Id": "6b10fa6d53463d039cdcc703b36ec894a79e34af4711db77f7a0583e3f78fcaa",
        "Created": "2021-07-07T12:51:17.348552541Z",
        "Path": "/bin/bash",
        "Args": [
            "-c",
            "/opt/scripts/iobroker_startup.sh"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-08-02T04:28:44.415535798Z",
            "FinishedAt": "2021-08-04T05:09:59.857722967Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2021-08-04T06:08:58.281172763+01:00",
                        "End": "2021-08-04T06:08:58.52088436+01:00",
                        "ExitCode": 0,
                        "Output": "Health status: OK - Main process (js-controller) is running.\n"
                    },
                    {
                        "Start": "2021-08-04T06:09:13.546592413+01:00",
                        "End": "2021-08-04T06:09:13.809108155+01:00",
                        "ExitCode": 0,
                        "Output": "Health status: OK - Main process (js-controller) is running.\n"
                    },
                    {
                        "Start": "2021-08-04T06:09:28.827057147+01:00",
                        "End": "2021-08-04T06:09:29.063713323+01:00",
                        "ExitCode": 0,
                        "Output": "Health status: OK - Main process (js-controller) is running.\n"
                    },
                    {
                        "Start": "2021-08-04T06:09:44.08246896+01:00",
                        "End": "2021-08-04T06:09:44.288740125+01:00",
                        "ExitCode": 0,
                        "Output": "Health status: OK - Main process (js-controller) is running.\n"
                    },
                    {
                        "Start": "2021-08-04T06:09:59.305768527+01:00",
                        "End": "2021-08-04T06:09:59.593402334+01:00",
                        "ExitCode": 0,
                        "Output": "Health status: OK - Main process (js-controller) is running.\n"
                    }
                ]
            }
        },
        "Image": "sha256:9987c0139cfa40d8e6f423f17fb19c5185ca7f6307f23a2edc43cad7e13049c9",
        "ResolvConfPath": "/var/lib/docker/containers/6b10fa6d53463d039cdcc703b36ec894a79e34af4711db77f7a0583e3f78fcaa/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6b10fa6d53463d039cdcc703b36ec894a79e34af4711db77f7a0583e3f78fcaa/hostname",
        "HostsPath": "/var/lib/docker/containers/6b10fa6d53463d039cdcc703b36ec894a79e34af4711db77f7a0583e3f78fcaa/hosts",
        "LogPath": "",
        "Name": "/iobroker",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "iobrokerdata:/opt/iobroker"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "journald",
                "Config": {}
            },
            "NetworkMode": "iobroker_default",
            "PortBindings": {
                "8081/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8081"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": [],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/6aa0070f365939d97ee5601e85c491e9ac68748094e977e1d6bc0a53420fc888-init/diff:/var/lib/docker/overlay2/d3f5764d65e7f3d4f8c7a46ce3fbe0c7530a610e0ab3b5a5e7c49c5bf28fbf2f/diff:/var/lib/docker/overlay2/b09a86d27dc4d99219a668c38b9a73d10627ffe1dd746ba13b7679f864ca4d81/diff:/var/lib/docker/overlay2/c5c4ad00b87c2446871ac18dece9f3530ba67aa01f04d06405ce345af0354cbe/diff:/var/lib/docker/overlay2/8a7a96d1c881858d8fc8aea52eb4bad2f6bed0d5aa95a9bf07d115fbc492760b/diff:/var/lib/docker/overlay2/dbcaceadae17bd26afba6252879e8c8be7b21af376b127cc29e058df46ee3246/diff:/var/lib/docker/overlay2/e6118e38bff831578a5af7e05350e658219f85f80c8074839112bc7808b13d87/diff:/var/lib/docker/overlay2/e95747690565bd6b5ee5bd4de0a8c3615e4045d64474fc9d306a02d1d3e5132d/diff:/var/lib/docker/overlay2/de875b0e3ec7f28aa5d7bd1f71abb735c8c78df3666dd163f14e686dc9f31181/diff:/var/lib/docker/overlay2/06d73f8156b98d1a16622b78989fb264b7c6c62384d3e4fb0528a65656633134/diff:/var/lib/docker/overlay2/d7c9f0f35e0147b58231d70cb4bad41165de7e51f223e2d0d61363fcfa19fa14/diff:/var/lib/docker/overlay2/a9c2ddb2b53c9fa6a93517681f2a2eb5c221efcda714c11964b03a3fe9ac39f7/diff:/var/lib/docker/overlay2/21369d498b82406d87d8063a969768b8435c617d7db1b78c379d44c9befd8851/diff:/var/lib/docker/overlay2/c2c28e6ec9f0ccc30f98cda10d082b798c7d140b25768e8151cb75f48a582a09/diff:/var/lib/docker/overlay2/031de0baf18032cdcbb0d0a44f503cf5a77311dfede328d296334ceeb75f8b3e/diff:/var/lib/docker/overlay2/0598666edba7810af21b388f6eb2ae3e6800aed77ac4910298c22552842ea67b/diff:/var/lib/docker/overlay2/11dcdbcee4eaae9e37ecdd4798f29b6691e3fcb71aed1da76114acc43be3aaa4/diff:/var/lib/docker/overlay2/1db3d2ed3376ae0afa5467b925f0f0e1cebbc760661c93712b480e9c2b7cfa7f/diff:/var/lib/docker/overlay2/fdda8a91af708d6f49c72002eac2469584f98cf73fc17e7d81e8e9000f170125/diff:/var/lib/docker/overlay2/4970f36eb9f9b45c261a69d6fa2eb24703453f99bba83efd0bd6a507c3058ae5/diff:/var/lib/docker/overlay2/44f80a4706fd57606d45429fa8631f10152e4274c43468ca1dab0d1cdf101b7e/diff:/var/lib/docker/overlay2/00b99bb0fc849aaf89e35d2e923f95c76397469aeff7992d93b7e0c4c753fd00/diff:/var/lib/docker/overlay2/f39b1b711017b28199375423f18567e8b25253e3344aaee60455117426addd20/diff:/var/lib/docker/overlay2/14c644bd3ff936afc8461e00cadbecc2656761ad1d6aea0104bc73e61d66ea91/diff:/var/lib/docker/overlay2/cfab81b45121492a24028c42e121d38ec268820ac3642e612d2334606f8d8db0/diff:/var/lib/docker/overlay2/39972a9c8c4a53530347eea70c049f06524b2ffe285d6bc8a68ec13cb9954cae/diff:/var/lib/docker/overlay2/c555d20fdd02652feb34ab47b79480d88a2b815688327d2db4374c4110bae725/diff:/var/lib/docker/overlay2/b8920022363b782db5b3eae7f00b41344ae8acf34a26e107ef01013158ac3122/diff:/var/lib/docker/overlay2/819674b2d7e70d8cc4ea009499277c68da9f21c44f731b9e4d87275130d827ad/diff:/var/lib/docker/overlay2/20031b32d7995affb931af349e00625f31593a4941af460df0b31691d019e304/diff:/var/lib/docker/overlay2/8002103efbc9b1f4f66d8b187aef71cc0c321856e1a590ae08855a4ab80edafc/diff",
                "MergedDir": "/var/lib/docker/overlay2/6aa0070f365939d97ee5601e85c491e9ac68748094e977e1d6bc0a53420fc888/merged",
                "UpperDir": "/var/lib/docker/overlay2/6aa0070f365939d97ee5601e85c491e9ac68748094e977e1d6bc0a53420fc888/diff",
                "WorkDir": "/var/lib/docker/overlay2/6aa0070f365939d97ee5601e85c491e9ac68748094e977e1d6bc0a53420fc888/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "iobrokerdata",
                "Source": "/var/lib/docker/volumes/iobrokerdata/_data",
                "Destination": "/opt/iobroker",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "iobroker",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8081/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LC_ALL=de_DE.UTF-8",
                "DEBIAN_FRONTEND=teletype",
                "UDEV=off",
                "LANG=de_DE.UTF-8",
                "LANGUAGE=de_DE:de",
                "SETGID=1000",
                "SETUID=1000",
                "TZ=Europe/Berlin"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "/bin/bash",
                    "-c",
                    "/opt/scripts/healthcheck.sh"
                ],
                "Interval": 15000000000,
                "Timeout": 5000000000,
                "Retries": 5
            },
            "Image": "buanet/iobroker:latest",
            "Volumes": null,
            "WorkingDir": "/opt/iobroker",
            "Entrypoint": [
                "/bin/bash",
                "-c",
                "/opt/scripts/iobroker_startup.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "847d65f08f322957dd75aa9b94cc78662bf1f5df",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "iobroker",
                "com.docker.compose.service": "iobroker",
                "com.docker.compose.version": "1.5.0",
                "io.balena.architecture": "armv7hf",
                "io.balena.qemu.version": "5.2.0+balena4-arm",
                "maintainer": "Andre Germann",
                "url": "https://buanet.de"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "cd93df40b8952a1654988d8b891fe29ee8fb9bd34248348d87ceae771af04337",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/cd93df40b895",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "iobroker_default": {
                    "IPAMConfig": {},
                    "Links": [],
                    "Aliases": [
                        "iobroker",
                        "6b10fa6d5346"
                    ],
                    "NetworkID": "7a29bc9007f8c114a5ba73eb8681a8bbb4977dfe7df9f40f6b323f1b27c79768",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by piksel** [comment]
Well, I guess you don't have the image locally somehow. That should be checked by watchtower, causing it to skip the container... Not sure why that isn't happening...

**Comment by boehser-enkel** [comment]
Okay deleted this one as i don't need it
Thanks for your help

**Comment by Dinth** [comment]
Sorry for digging out the old thread, but just wanted to add that the exact same error shows up when the image is set to "depend on" itself.
The error was quite uninformative, and while it was caused by my own typo, it took me a while to troubleshoot.

**Comment by piksel** [comment]
@Dinth oh, right. Even though this looks the same I think it's another issue. Would you mind opening another ticket with the error? I think I understand what is going wrong here, but I need some details to verify...
