### ISSUE TITLE
Portainer Disappeared After Update

### ISSUE THREAD

**Issue by hirenshah** [containrrr/watchtower#584]
**Describe the bug**
WatchTower is configured with --schedule to check daily for updates at 00:00.  I noticed this morning that I couldn't access Portainer, and subsequently discovered that the container was no longer present.

I have all my `docker run -d` commands saved, and volumes mounted for any data, so was able to get Portainer back again within minutes.  

I found the below mentioned logs in WatchTower.

**Expected behavior**
The Portainer container to be recreated with the updated image.

**Environment**
 - Platform = Synology NAS DS1813+
 - Architecture = x86-64
 - Docker version = 19.03.11

**Logs from running watchtower with the `--debug` option**
```
time="2020-06-17T00:00:02+01:00" level=debug msg="Pulling portainerci/portainer:develop for /Portainer"
time="2020-06-17T00:00:02+01:00" level=debug msg="Loaded auth credentials for user ********* on registry portainerci/portainer:develop"
time="2020-06-17T00:00:02+01:00" level=debug msg="Got image name: portainerci/portainer:develop"
time="2020-06-17T00:00:15+01:00" level=info msg="Found new portainerci/portainer:develop image (sha256:ee07cae635877c0e5bd730dff415ea1380b1f3334c896924b1d6cbd6f983ca5a)"
time="2020-06-17T00:00:20+01:00" level=info msg="Stopping /Portainer (d8876b6c4a93813738dc39ed39899acb856b0beb05b7a991111b99c068444433) with SIGTERM"
time="2020-06-17T00:00:21+01:00" level=debug msg="Removing container d8876b6c4a93813738dc39ed39899acb856b0beb05b7a991111b99c068444433"
2020/06/17 00:00:21 cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00040e190)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:161 +0x9e
panic(0xacd1e0, 0x1127b00)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/containrrr/watchtower/pkg/container.Container.runtimeConfig(0x100, 0xc000316f60, 0x0, 0x0)
	/go/watchtower/pkg/container/container.go:169 +0x4e
github.com/containrrr/watchtower/pkg/container.dockerClient.StartContainer(0xcb4e80, 0xc0002ca700, 0x1, 0x900100, 0xc000316f60, 0x0, 0x1, 0xc000340100, 0xc000316f60, 0x0)
	/go/watchtower/pkg/container/client.go:163 +0x86
github.com/containrrr/watchtower/internal/actions.restartStaleContainer(0x1b550100, 0xc000316f60, 0x0, 0xca5960, 0xc0002d0c00, 0xc0002c7810, 0x1, 0x6fc23ac00, 0x0)
	/go/watchtower/internal/actions/update.go:121 +0xdb
github.com/containrrr/watchtower/internal/actions.restartContainersInSortedOrder(0xc0004ba000, 0x5, 0x8, 0xca5960, 0xc0002d0c00, 0xc0002c7810, 0x1, 0x6fc23ac00, 0x0)
	/go/watchtower/internal/actions/update.go:96 +0x241
github.com/containrrr/watchtower/internal/actions.Update(0xca5960, 0xc0002d0c00, 0xc0002c7810, 0x1, 0x6fc23ac00, 0x0, 0xed679f761, 0x2000300010000)
	/go/watchtower/internal/actions/update.go:53 +0x37a
github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0xc0002c7810)
	/go/watchtower/cmd/root.go:206 +0xbe
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()
	/go/watchtower/cmd/root.go:163 +0xb6
github.com/robfig/cron.FuncJob.Run(0xc0004056a0)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:92 +0x25
github.com/robfig/cron.(*Cron).runWithRecovery(0xc00040e190, 0xc8f160, 0xc0004056a0)
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:165 +0x59
created by github.com/robfig/cron.(*Cron).run
	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:199 +0x747
```

**Additional context**
Image = `containrrr/watchtower:latest-dev`

**Comment by simonaronsson** [comment]
Hi!

To be able to help you, it would be really helpful if you would provide the command you used to launch watchtower.

Thanks,
Simme

**Comment by thelittlefireman** [comment]
hi, i've got the same issue : 
```
time="2020-07-14T20:29:34+02:00" level=info msg="Stopping /bitwardenrs (4c92c2c32e227c9477e7b138b1f0369998980ede0e65792e9afcf213d88c8892) with SIGTERM"


2020/07/14 20:29:48 cron: panic running job: runtime error: invalid memory address or nil pointer dereference


goroutine 113 [running]:


github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc0000b8320)


	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:161 +0x9e


panic(0xacd1e0, 0x1127b00)


	/usr/local/go/src/runtime/panic.go:969 +0x166


github.com/containrrr/watchtower/pkg/container.Container.runtimeConfig(0x100, 0xc0003a7950, 0x0, 0x43baa8)


	/go/watchtower/pkg/container/container.go:169 +0x4e


github.com/containrrr/watchtower/pkg/container.dockerClient.StartContainer(0xcb4e80, 0xc000360700, 0x1, 0x100, 0xc0003a7950, 0x0, 0x1, 0xc000200100, 0x0, 0xc0003e5568)


	/go/watchtower/pkg/container/client.go:163 +0x86


github.com/containrrr/watchtower/internal/actions.restartStaleContainer(0x60fa0100, 0xc0003a7950, 0x0, 0xca5960, 0xc00036ab80, 0xc00035d870, 0x0, 0x2540be400, 0x0)


	/go/watchtower/internal/actions/update.go:121 +0xdb


github.com/containrrr/watchtower/internal/actions.restartContainersInSortedOrder(0xc00009c600, 0x1a, 0x20, 0xca5960, 0xc00036ab80, 0xc00035d870, 0x0, 0x2540be400, 0x0)


	/go/watchtower/internal/actions/update.go:96 +0x241


github.com/containrrr/watchtower/internal/actions.Update(0xca5960, 0xc00036ab80, 0xc00035d870, 0x0, 0x2540be400, 0x0, 0x0, 0x10)


	/go/watchtower/internal/actions/update.go:53 +0x37a


github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0xc00035d870)


	/go/watchtower/cmd/root.go:206 +0xbe


github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()


	/go/watchtower/cmd/root.go:163 +0xb6


github.com/robfig/cron.FuncJob.Run(0xc0003edf40)


	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:92 +0x25


github.com/robfig/cron.(*Cron).runWithRecovery(0xc0000b8320, 0xc8f160, 0xc0003edf40)


	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:165 +0x59


created by github.com/robfig/cron.(*Cron).run


	/go/pkg/mod/github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967/cron.go:199 +0x747


time="2020-07-14T20:33:58+02:00" level=info msg="Unable to update container /kibana. Proceeding to next."


time="2020-07-14T20:33:59+02:00" level=info msg="Unable to update container /logstash. Proceeding to next."


time="2020-07-14T20:34:06+02:00" level=info msg="Unable to update container /pfelk03. Proceeding to next."


time="2020-07-14T20:34:07+02:00" level=info msg="Unable to update container /pfelk01. Proceeding to next."


time="2020-07-14T20:34:08+02:00" level=info msg="Unable to update container /pfelk02. Proceeding to next."


time="2020-07-14T20:34:23+02:00" level=info msg="Unable to update container /home-assistant. Proceeding to next."


time="2020-07-14T20:34:26+02:00" level=info msg="Unable to update container /SpringBootRappelProduitsPROD. Proceeding to next."


time="2020-07-14T20:38:58+02:00" level=info msg="Unable to update container /kibana. Proceeding to next."


time="2020-07-14T20:38:59+02:00" level=info msg="Unable to update container /logstash. Proceeding to next."


time="2020-07-14T20:39:05+02:00" level=info msg="Unable to update container /pfelk03. Proceeding to next."


time="2020-07-14T20:39:06+02:00" level=info msg="Unable to update container /pfelk01. Proceeding to next."


time="2020-07-14T20:39:08+02:00" level=info msg="Unable to update container /pfelk02. Proceeding to next."


time="2020-07-14T20:39:22+02:00" level=info msg="Unable to update container /home-assistant. Proceeding to next."


time="2020-07-14T20:39:25+02:00" level=info msg="Unable to update container /SpringBootRappelProduitsPROD. Proceeding to next."


time="2020-07-14T20:43:58+02:00" level=info msg="Unable to update container /kibana. Proceeding to next."


time="2020-07-14T20:43:59+02:00" level=info msg="Unable to update container /logstash. Proceeding to next."


time="2020-07-14T20:44:06+02:00" level=info msg="Unable to update container /pfelk03. Proceeding to next."


time="2020-07-14T20:44:07+02:00" level=info msg="Unable to update container /pfelk01. Proceeding to next."


time="2020-07-14T20:44:08+02:00" level=info msg="Unable to update container /pfelk02. Proceeding to next."


time="2020-07-14T20:44:23+02:00" level=info msg="Unable to update container /home-assistant. Proceeding to next."


time="2020-07-14T20:44:26+02:00" level=info msg="Unable to update container /SpringBootRappelProduitsPROD. Proceeding to next."


time="2020-07-14T20:48:58+02:00" level=info msg="Unable to update container /kibana. Proceeding to next."


time="2020-07-14T20:49:00+02:00" level=info msg="Unable to update container /logstash. Proceeding to next."


time="2020-07-14T20:49:08+02:00" level=info msg="Unable to update container /pfelk03. Proceeding to next."


time="2020-07-14T20:49:09+02:00" level=info msg="Unable to update container /pfelk01. Proceeding to next."


time="2020-07-14T20:49:11+02:00" level=info msg="Unable to update container /pfelk02. Proceeding to next."


time="2020-07-14T20:49:26+02:00" level=info msg="Unable to update container /home-assistant. Proceeding to next."


time="2020-07-14T20:49:29+02:00" level=info msg="Unable to update container /SpringBootRappelProduitsPROD. Proceeding to next."


time="2020-07-14T20:53:58+02:00" level=info msg="Unable to update container /kibana. Proceeding to next."


time="2020-07-14T20:54:00+02:00" level=info msg="Unable to update container /logstash. Proceeding to next."


time="2020-07-14T20:54:06+02:00" level=info msg="Unable to
```

And that's my config : 

```
  watchtower:
    image: containrrr/watchtower:latest-dev
    container_name: watchtower
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_CLEANUP=false
      - WATCHTOWER_DEBUG=false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - monitor-net
```

**Comment by piksel** [comment]
`/go/watchtower/pkg/container/container.go:169 +0x4e` would indicate that `c.imageInfo` is nil for some reason. Not sure what to make of that though...

**Comment by thelittlefireman** [comment]
Any news ?

**Comment by hirenshah** [comment]
> Hi!
> 
> To be able to help you, it would be really helpful if you would provide the command you used to launch watchtower.
> 
> Thanks,
> Simme

```
docker run -d \
  --privileged \
  --name=WatchTower \
  -e TZ=Europe/London \
  --log-driver=json-file \
  --log-opt max-size=25m \
  --log-opt max-file=5 \
  --restart=unless-stopped \
  -v /volume1/docker/docker.sock:/var/run/docker.sock \
  containrrr/watchtower:latest \
  --cleanup \
  --schedule "0 0 0 * * *" \
  --stop-timeout 30s
```

**Comment by thelittlefireman** [comment]
i add some informations :
Docker version 18.09.8, build bfed4f5
docker-compose version 1.24.0, build 0aa59064

**Comment by piksel** [comment]
The issue is a change in dev that causes the error. Don't use `containrrr/watchtower:latest-dev` unless you want to test the bleeding edge 😁. That being said, it helped us find the bug, so that's appreciated!

Try changing to `containrrr/watchtower:latest`
